[package]
name = "wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
chip8_core = { path = "../chip8_core" }
js-sys = "ˆ0.3.46"
wasm-bindgen = "ˆ0.2.69"


[dependencies.web-sys]
version = "ˆ0.3.46"
features = [
"KeyboardEvent"
]